# Config file used to set up forecast analysis
#

start_time: "2024-01-01T00:00:00Z" # first forecast time
end_time: "2024-12-31T23:00:00Z" # last forecast time
bbox: '[37,-111,46,-95]' # spatial bounding box
climatology_file: "data/climatology_rockymtn_2024_forecasts.pkl" # name of climatology output to be used for comparison
raws_file: "data/raws_rocky_2024.pkl" # all observed RAWS FMC in 2024 for given bbox
