# Config file used to set up forecast analysis
#

f_start: "2024-01-01T00:00:00Z" # first forecast time
f_end: "2024-01-04T23:00:00Z" # last forecast time
forecast_hours: 48 # number of hours to run forecast before re-initializing (matters for RNN and ODE baseline, has no effect on static ML models nor on climatology). Hours determined by max forecast window of HRRR
n_reps: 10 # Number of replications to train/forecast, used to estimate uncertainty in forecast accuracy metrics
train_start: "2023-12-01T00:00:00Z" # first time for training
train_end: "2023-12-31T23:00:00Z" # last time for training
space_test_frac: 0.1 # Percentage of data based on location for val and test
bbox: '[37,-111,46,-95]' # spatial bounding box
features_list: ['Ed', 'Ew', 'solar', 'wind', 'elev', 'lon', 'lat', 'rain', 'hod', 'doy'] # inputs to ML models
baselines: ['ode', 'xgb', 'climatology'] # Names of models to be run on same data for comparison. USE None if only running RNN
climatology_file: "data/climatology_rockymtn_2024_forecasts.pkl" # name of climatology output to be used for comparison
data_dir: "data/rocky_fmda" # Directory for formatted FMDA data dictionaries 
